### ISSUE TITLE
LPE + PX4FLow Improving performance and Failsafe options?

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#10]
Hello Nuno
I read here 
https://github.com/PX4/Firmware/issues/6957
that james goppert (whom I think is a pretty experienced developer too) uses gyro compensation and land detector. 
Q1. We haven't enabled those options, would they help?

I'm also interested in a comment by Jgoppert where  it seems Land Detector provides some sort of failsafe option when PX4Flow fails. From one of his replies:

`There is a hand off when you takeoff from the land detector to the optical flow. If the optical flow doesn't get good data after takeoff, it will attempt to land if in auto, or fallback to altitude control mode if in position control.`

Q3. Is this behaviour still current? Or are the other failsafes?  Interested in understanding what happens when we loose Flow or Vision or both? Currently we seem to crash ... :-(

**Comment by TSC21** [comment]
> Q1. We haven't enabled those options, would they help?

Land detector actually helps in getting an initial state set. It basically forces a state on the kalman fitler where the velocity is zero and the AGL is 0. So it is useful as an initial state, but can cause trouble if you actually land and then takeoff again without resetting the position estimator.

> it will attempt to land if in auto, or fallback to altitude control mode if in position control.

This does not currently happen unless you switch to LAND mode. There's currently no failsafe for sensor faults or timeouts on LPE, but you have `COM_POS_FS_DELAY` that influences here: https://github.com/PX4/Firmware/blob/bc3577bd60573b6c1e9f80024659805498e7608b/src/modules/commander/commander.cpp#L2158-L2159 (for altitude only).

Q3. Is this behaviour still current? Or are the other failsafes? Interested in understanding what happens when we loose Flow or Vision or both? Currently we seem to crash ... :-(

The answer is above. Currently there is no actual mechanism to verify the position validation flags and trigger a failsafe cause it is not easy to detect between false positives and bad estimations.
