### ISSUE TITLE
QGC - Fake GPS ?

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#17]
Hello Nuno

I have used in the past Mission/Auto mode with QGC on an outdoor drone and it worked great. 

I was thinking that using Mission mode indoors with QGC might be quite practical, and I know you said it doesn't work with local position, but I remember reading somewhere about a a fake GPS module in PX4? Does that still exist?
My thought was that it would be great to send our RPLidar based position estimation as fake GPS to the PX4 to be able to use QGC.

Alternatively you mentioned we could calculate our own GPS positions from the local_positions by scaling them, does that mean that the PX4 itself also internally converts the local positions to GPS coordinates?

**Comment by TSC21** [comment]
PX4 does not have a fake GPS module. PX4 has a `geo` lib (https://github.com/PX4/Firmware/tree/master/src/lib/geo) that handles the reprojection from local to geographic coordinates.
For feeding a fake GPS position you can use MAVROS [`fake_gps` plugin](https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/fake_gps.cpp), that automatically converts from local ENU to geographic LLA coordinates - so basically you can feed the vision estimation to it and it converts that estimation to LLA in a `HIL_GPS` msg, that is sent to the FCU. So that PX4 accepts it, you need to set `MAV_USEHILGPS` parameter so it accepts `HIL_GPS` msgs but without being on HIL mode.

**Comment by bto-ealdaz** [comment]
Fantastic, that’s the plugin I was thinking about, but couldn’t find it when i was looking earlier. 
Thanks I’ll take a look and try.


Eduardo

---

Eduardo Aldaz Carroll
CTO
BeTomorrow UK

E: eduardo.aldaz@betomorrow.com
M: +44 (0) 7543 519191
Skype: e.aldaz-carroll

**Comment by bto-ealdaz** [comment]
Does this plugin automatically subscribe to the vision topic and publish in a gps topic?

Or do we need to enable it somehow in px4_config.yml and tell it what topic to expect the data from ( vision or mocap ? )


Thanks

Eduardo

---

Eduardo Aldaz Carroll
CTO
BeTomorrow UK

E: eduardo.aldaz@betomorrow.com
M: +44 (0) 7543 519191
Skype: e.aldaz-carroll

**Comment by TSC21** [comment]
You need to configure it on `px4_config.yaml` so it subscribes to the vision topic. The plugin has a lot of customizeble elements.
