### ISSUE TITLE
Flight with EKF2 + Flow + Vision - Successful position hold

### ISSUE THREAD

**Issue by bto-ealdaz** [BeTomorrowUK/Firmware#4]
https://logs.px4.io/plot_app?log=cb4d1757-0d7e-4ec8-a9fe-a03f51e34267
We had very good behaviour in general, position hold was pretty decent. And vision data matches well local position data, so it seems it was used ( i.e. it was not all done with PX4flow data)

The modifications we did where:
1.- Fixed heading issues. Now on takeoff the drone is facing east and vision provides heading as 90, so matches magnetic.
2.- Increased OF quality min to 150 ( was 1)
3.- Changed optical flow parameters to improve performance with our office floors. (Previously we only had acceptable performance over a grass carpet)
    Brightness=30 ( was 20)
    BFLOW_F_THRD=20 (was 40)
    BFLOW_V_THRD = 7000 (was 5000)

4.- We increased the gate vision to 15SD from 5SD.

The flight was as follows:
We first set it in Altitude hold, checked operation. Then in Position hold, let it hover for a while. And then fly in N-S direction, then in E-W direction ( this allows us to check that the vision direction vectors are aligned with the other sensors). Then we flew up and down fast ( lost vision as a result).
Finally we ventured into the forbidden carpet-less zone… and hovered happily !! Which was a first for us.

Video here: https://www.dropbox.com/s/ev8y2l3ecg9gqfd/OF%2BVision-OK.mov?dl=0

Our main questions are:
1.- Is 15SD a normal amount for the gate? Seems to big. But at 5SD it does not seem like the vision data is taken into account ( then again it might have been because previously we had yaw issues, and haven't tested separately)

2.- When you look at the log data does it all seem normal, or do you spot weird behaviour?

Thanks!

**Comment by TSC21** [comment]
Log looks good. I still think you should try to fuse vision yaw. Also, I like the idea of the carpet, but it doesn't really have those many noticeable features or patterns. Something like this would increase your flow performance: http://www.publicdomainpictures.net/pictures/120000/velka/seamless-carpet-pattern-1425829108zuX.jpg. Of course you won't have this all way in real situations, but also leaves you with the idea of the performance.
Another way you can actually increase the performance: add a diffuse LED light point downwards. This will improve two things: the illumination of the plane where the camera detects the features; 2nd, it will also eliminate the vehicle's own shadow, which by experience leads to having a drift and decrease of the velocity estimation performance. I say diffuse because you don't want a directional light reflecting on the floor or marking a big light "dot", which tricks the flow estimation.

**Comment by bto-ealdaz** [comment]
Interesting, we are fusing vision yaw, is there something in the log that indicates it's not working?

We were also surprised that the grass carpet worked well, in fact works much better than our vinyl floor which has a very clear wood pattern (we thought it would work great) but for some reason the optical flow didn't seem to like it. 
Today we are going to adjust exposure also in the px4flow and see if that helps with the wood floor.

Thanks for the suggestion of the LED light, good idea!

I like the carpet design on that link !... we will buy some low coffee tables and a water pipe and we're all set ! ;-)

**Comment by TSC21** [comment]
> Interesting, we are fusing vision yaw, is there something in the log that indicates it's not working?

Not really. I thought since you were aligning the the vehicle that actually you were not fusing the yaw.

**Comment by TSC21** [comment]
> in fact works much better than our vinyl floor which has a very clear wood pattern

Isn't the vinyl floor a little reflective? Carpet is not so you get better results, even with less features.

**Comment by bto-ealdaz** [comment]
It doesn't seem to be reflective from what I can tell, but will do more tests.
